###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "ana",
    "email": "ana@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "irene@gmail.com",
    "password": "12345"
}


